[config]
schemaVersion = "0.0.1"

[package]
namespace = "drknowsalot"
name = "drknowsalot_EDM_Radio"
versionNumber = "1.0.0"
description = "A variety of EDM radios for ExtendedRadio."
websiteUrl = "https://github.com/drknowsalot/cs2-edm-radio"
containsNsfwContent = false

[package.dependencies]
# BepInEx-BepInExPack = "5.4.2100"
# CaptainOfCoit-HookUI = "0.3.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./ts-build"

[publish]
repository = "https://thunderstore.io"
communities = [ "cities-skylines-ii", ]
categories = [ "mods" ]
